### ISSUE TITLE
is this possible to use LUA client with fast-tcp server?

### ISSUE THREAD

**Issue by takaaptech** [alemures/fast-tcp#1]
I see fast-tcp is awesome! Can we connect client from LUA (mobile game engine using LUA) to fast-tcp server?
Thank so much!

**Comment by alemures** [comment]
Hi @takaaptech , fast-tcp was written only for node.js and at the moment there aren't any client in other language than node. Maybe I'll write a java client in a close future but I can't help you in this case because I have no clue about LUA.
