### ISSUE TITLE
Login event

### ISSUE THREAD

**Issue by lfernando-silva** [alemures/fast-tcp#2]
Docs doesn't descibe the login event an its handling...

**Comment by alemures** [comment]
Hi @lfernando-silva, there isn't any event called "login" unless you implement your own one. The default events that the class "Socket" fires are listed in the documentation:

Socket#event:connect
Socket#event:reconnecting
Socket#event:socket_connect
Socket#event:socket_drain
Socket#event:end
Socket#event:close
Socket#event:error

**Comment by lfernando-silva** [comment]
Ah thats ok so, sorry about! Thank you
