### ISSUE TITLE
BinaryStream from Socket not working

### ISSUE THREAD

**Issue by TomFuch** [alemures/fast-tcp#3]
In the following sample code no messages are sent after the 10th or 11th run.
Tested on MacOS 10.12.4 / Node 6.10.x / Electron 1.6.7

SERVER:

```javascript
import { createWriteStream } from "fs";

const server = new Server();

server.on('connection', (socket) => {
    console.log('connected');

    socket.on('image', function (readStream, info, callback) {
        const rootPath = '/Users/thomas/Documents/Temp/';

        let writeStream = createWriteStream(rootPath + info.name);

        readStream.pipe(writeStream);

        writeStream.on('finish', () => {
            callback('image transfer successfully');
        });
    });

});

server.listen(5000);
```

CLIENT:

```javascript
import { createReadStream } from "fs";

const socket = new Socket({
    host: 'localhost',
    port: 5000
});

socket.on('connect', () => {
    let counter = 1;

    setInterval(() => {
        const testFile = '/Users/thomas/Documents/test.jpg';

        let writeStream = socket.stream('image', { name: Math.random() + '-test.jpg' }, (result) => {
            console.log('answer from server: ', result);
        });

        createReadStream(testFile).pipe(writeStream);

        console.log('file transfered: ', counter);

        counter++;

    }, 5000);

});
```

**Comment by alemures** [comment]
Hi @TomFuch I just ran your code for a while and it was able to reach 300 transferred images without any problem on Ubuntu 16.04 and node 6.10.2.

I have never used Electron before, Could Electron being stopping network operations after a while? Is the client printing "file transferred" every time? Is the server receiving the "image" event every time  but the writableStream is not getting the event "finish" (that would explain why you stop seeing logs in the server)?

**Comment by TomFuch** [comment]
Hi Alejandro! 

I've tested the whole thing again without Electron. I have found that when I run the server and the client in the same Nodeprocess (the whole Thing in one JS file) everything works as desired.
As soon as the server and the client run in a separate Nodeprocess (two separate JS files) the problem occurs ... I hope this helps you further. 
Kind regards

**Comment by TomFuch** [comment]
Hi Alejandro! 

I have the transmission now still with another operating system tested and it has immediately worked. 150 - 300 passes were not a problem at all.
Since the problem only on macOS locally occurs, I am almost sure that the problem can not lie to fast-tcp. Sorry for that! I think you can close the ticket.
Kind regards

**Comment by alemures** [comment]
Hi Tom, I could reproduce the issue on Ubuntu 16.04. Having the client sending every 5 seconds, it was able to send 10 or 11 before it stopped but at the same time, sending every 500ms it was able to send around 80. It seems like the server stop getting images after N seconds.

That's a weird behavior so, I'll run few more tests to get more info.

**Comment by TomFuch** [comment]
Hi ... I've discovered something. 
If in the exact same code under Windows start everything works normally. Even if I start the server under Windows and the client under macOS also works everything. For me, there are only problems when I start server and client locally on macOS ... This is really weird. For me, it looks almost like there is a problem under macOS with NODE.JS …
